import { SummaryLength, AnalysisResult, GeneratedContent, VideoMetadata } from "../types";

const API_BASE_URL = "http://127.0.0.1:5000";

interface AnalyzeResponse {
  metadata: VideoMetadata;
  analysis: AnalysisResult;
  assets: GeneratedContent;
}

export const analyzeVideoContent = async (
  videoUrl: string,
  length: SummaryLength,
  language: string = 'ko'
): Promise<{ metadata: VideoMetadata; analysis: AnalysisResult; assets: GeneratedContent }> => {
  const response = await fetch(`${API_BASE_URL}/api/analyze`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      url: videoUrl,
      length: length,
      language: language,
    }),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({ detail: "Unknown error" }));
    throw new Error(error.detail || `API error: ${response.status}`);
  }

  const data: AnalyzeResponse = await response.json();
  return data;
};

export const generateKnowledgeAssets = async (
  analysis: AnalysisResult,
  title: string
): Promise<GeneratedContent> => {
  // Assets are already generated by the analyze endpoint
  // This function is kept for backwards compatibility
  return {
    blog: `# ${title}\n\n${analysis.summary}`,
    sns: {
      twitter: `Check out: ${title}`,
      linkedin: `Insights from: ${title}`,
      instagram: `🎬 ${title} #video`,
    },
    newsletter: `Today's highlight: ${title}\n\n${analysis.summary}`,
  };
};

export const chatWithVideo = async (
  query: string,
  context: string,
  history: { role: string; parts: { text: string }[] }[],
  language: string = 'ko'
): Promise<string> => {
  const response = await fetch(`${API_BASE_URL}/api/chat`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      query,
      context,
      language,
      history: history.map(h => ({
        role: h.role,
        content: h.parts.map(p => p.text).join("\n"),
      })),
    }),
  });

  if (!response.ok) {
    return language === 'ko'
      ? "영상 내용을 기반으로 답변을 찾을 수 없습니다."
      : "I couldn't find an answer for that based on the video content.";
  }

  const data = await response.json();
  return data.response || (language === 'ko'
    ? "영상 내용을 기반으로 답변을 찾을 수 없습니다."
    : "I couldn't find an answer for that based on the video content.");
};
