import React, { useState } from 'react';
import {
  FileText,
  Share2,
  Download,
  Copy,
  Twitter,
  Linkedin,
  Check,
  ExternalLink,
  Clock,
  Eye,
  MessageSquare,
  Tag,
  Sparkles,
  BookOpen
} from 'lucide-react';
import { VideoMetadata, AnalysisResult, GeneratedContent } from '../types';
import { getTranslations, Language } from '../translations';
import ChatModal from './ChatModal';

interface AnalysisDisplayProps {
  metadata: VideoMetadata;
  analysis: AnalysisResult;
  assets: GeneratedContent;
  language: Language;
}

const AnalysisDisplay: React.FC<AnalysisDisplayProps> = ({ metadata, analysis, assets, language }) => {
  const t = getTranslations(language);
  const [activeAssetTab, setActiveAssetTab] = useState<'blog' | 'social'>('blog');
  const [copiedField, setCopiedField] = useState<string | null>(null);
  const [isChatOpen, setIsChatOpen] = useState(false);
  const [showShareMenu, setShowShareMenu] = useState(false);

  // Guard clauses for missing data
  if (!metadata || !analysis || !assets) {
    return (
      <div className="p-8 text-center text-gray-500">
        {language === 'ko' ? '데이터를 불러오는 중 오류가 발생했습니다.' : 'Error loading analysis data.'}
      </div>
    );
  }

  const handleCopy = (text: string, field: string) => {
    navigator.clipboard.writeText(text);
    setCopiedField(field);
    setTimeout(() => setCopiedField(null), 2000);
  };

  const handleExportMarkdown = () => {
    const content = `# ${metadata.title || 'Video Analysis'}

## Summary
${analysis.summary || ''}

## Key Insights
${(analysis.takeaways || []).map((insight, i) => `${i + 1}. ${insight}`).join('\n')}

## Chapters
${(analysis.timestamps || []).map(ts => `- **${ts.label}** (${ts.time})`).join('\n')}

## Blog Post
${assets.blog || ''}

---
*Generated by V-Core*
`;
    // ... (rest of export logic)
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(metadata.title || 'analysis').replace(/[^a-zA-Z0-9]/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-8 max-w-7xl mx-auto animate-in fade-in duration-500">
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6">
          <div className="glass-card rounded-2xl p-6 border border-white/10">
            <div className="flex gap-6">
              <a
                href={metadata.url}
                target="_blank"
                rel="noopener noreferrer"
                className="flex-shrink-0 relative group"
              >
                <img
                  src={metadata.thumbnail || ''}
                  alt={metadata.title}
                  className="w-48 h-28 object-cover rounded-xl bg-gray-800"
                />
                <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity rounded-xl flex items-center justify-center">
                  <ExternalLink className="text-white" size={24} />
                </div>
              </a>
              <div className="flex-1">
                <h1 className="text-xl font-bold text-white mb-2 line-clamp-2">{metadata.title}</h1>
                <p className="text-gray-500 text-sm mb-3">{metadata.channelTitle}</p>
                <div className="flex items-center gap-4 text-xs text-gray-400">
                  <span className="flex items-center gap-1">
                    <Clock size={14} />
                    {metadata.duration || 'N/A'}
                  </span>
                  <span className="flex items-center gap-1">
                    <Eye size={14} />
                    {metadata.views?.toLocaleString() || 'N/A'}
                  </span>
                </div>
              </div>
              <div className="relative">
                <button
                  onClick={() => setShowShareMenu(!showShareMenu)}
                  className="p-3 bg-white/5 rounded-xl hover:bg-white/10 transition-colors"
                >
                  <Share2 size={18} />
                </button>
                {showShareMenu && (
                  <div className="absolute right-0 mt-2 w-48 bg-zinc-800 rounded-xl border border-white/10 shadow-xl z-10">
                    <button
                      onClick={() => { handleExportMarkdown(); setShowShareMenu(false); }}
                      className="w-full flex items-center gap-2 px-4 py-3 hover:bg-white/5 transition-colors rounded-t-xl"
                    >
                      <Download size={16} />
                      {t.exportMarkdown}
                    </button>
                    <button
                      onClick={() => { handleCopy(analysis.summary || '', 'summary'); setShowShareMenu(false); }}
                      className="w-full flex items-center gap-2 px-4 py-3 hover:bg-white/5 transition-colors"
                    >
                      <Copy size={16} />
                      {language === 'ko' ? '요약 복사' : 'Copy Summary'}
                    </button>
                    <button
                      onClick={() => { window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(assets.sns.twitter || '')}`, '_blank'); setShowShareMenu(false); }}
                      className="w-full flex items-center gap-2 px-4 py-3 hover:bg-white/5 transition-colors rounded-b-xl"
                    >
                      <Twitter size={16} />
                      Twitter
                    </button>
                  </div>
                )}
              </div>
            </div>
          </div>

          <div className="glass-card rounded-2xl p-6 border border-white/10">
            <h2 className="text-lg font-bold mb-4 flex items-center gap-2">
              <FileText size={20} className="text-lime-400" />
              {t.summaryTitle}
            </h2>
            <p className="text-gray-300 leading-relaxed">{analysis.summary || 'No summary available.'}</p>
          </div>

          <div className="glass-card rounded-2xl p-6 border border-white/10">
            <h2 className="text-lg font-bold mb-4 flex items-center gap-2">
              <Sparkles size={20} className="text-lime-400" />
              {t.insightsTitle}
            </h2>
            <div className="space-y-3">
              {(analysis.takeaways || []).map((insight, i) => (
                <div key={i} className="flex gap-3 items-start">
                  <div className="w-6 h-6 bg-lime-400/20 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
                    <span className="text-xs font-bold text-lime-400">{i + 1}</span>
                  </div>
                  <p className="text-gray-300">{insight}</p>
                </div>
              ))}
              {(!analysis.takeaways || analysis.takeaways.length === 0) && (
                <p className="text-gray-500 italic">No insights available.</p>
              )}
            </div>
          </div>

          <div className="glass-card rounded-2xl p-6 border border-white/10">
            <h2 className="text-lg font-bold mb-4 flex items-center gap-2">
              <Clock size={20} className="text-lime-400" />
              {t.logicalChapters}
            </h2>
            <div className="space-y-2">
              {(analysis.timestamps || []).map((ts, i) => (
                <div key={i} className="flex items-center gap-4 p-3 bg-white/5 rounded-xl hover:bg-white/10 transition-colors">
                  <span className="text-lime-400 font-mono text-sm min-w-[60px]">{ts.time}</span>
                  <span className="text-gray-300">{ts.label}</span>
                </div>
              ))}
              {(!analysis.timestamps || analysis.timestamps.length === 0) && (
                <p className="text-gray-500 italic">No chapters available.</p>
              )}
            </div>
          </div>
        </div>

        <div className="space-y-6">
          <div className="glass-card rounded-2xl p-6 border border-white/10">
            <h2 className="text-lg font-bold mb-4 flex items-center gap-2">
              <MessageSquare size={20} className="text-lime-400" />
              {t.askIntelligence}
            </h2>
            <p className="text-gray-400 text-sm mb-4">{t.askAI}</p>
            <button
              onClick={() => setIsChatOpen(true)}
              className="w-full bg-lime-400 text-black rounded-xl py-3 font-bold hover:bg-lime-300 transition-colors"
            >
              {t.chatTitle}
            </button>
          </div>

          <div className="glass-card rounded-2xl p-6 border border-white/10">
            <h2 className="text-lg font-bold mb-4 flex items-center gap-2">
              <Tag size={20} className="text-lime-400" />
              {t.keywordsSectionTitle}
            </h2>
            <div className="flex flex-wrap gap-2">
              {(analysis.keywords || []).map((keyword, i) => (
                <span key={i} className="px-3 py-1 bg-white/5 rounded-full text-sm text-gray-300">
                  {keyword}
                </span>
              ))}
            </div>
          </div>

          <div className="glass-card rounded-2xl p-6 border border-white/10">
            <h2 className="text-lg font-bold mb-4 flex items-center gap-2">
              <BookOpen size={20} className="text-lime-400" />
              {t.assetsTitle}
            </h2>

            <div className="flex gap-2 mb-4">
              <button
                onClick={() => setActiveAssetTab('blog')}
                className={`px-3 py-1 rounded-lg text-sm font-medium transition-colors ${activeAssetTab === 'blog' ? 'bg-lime-400 text-black' : 'bg-white/5 text-gray-400'
                  }`}
              >
                {t.blogTab}
              </button>
              <button
                onClick={() => setActiveAssetTab('social')}
                className={`px-3 py-1 rounded-lg text-sm font-medium transition-colors ${activeAssetTab === 'social' ? 'bg-lime-400 text-black' : 'bg-white/5 text-gray-400'
                  }`}
              >
                {t.socialTab}
              </button>
            </div>

            {activeAssetTab === 'blog' && (
              <div className="relative">
                <p className="text-sm text-gray-300 whitespace-pre-wrap max-h-60 overflow-y-auto">
                  {assets.blog || 'No blog post generated.'}
                </p>
                <button
                  onClick={() => handleCopy(assets.blog || '', 'blog')}
                  className="absolute top-2 right-2 p-2 bg-zinc-800 rounded-lg hover:bg-zinc-700"
                >
                  {copiedField === 'blog' ? <Check size={14} className="text-lime-400" /> : <Copy size={14} />}
                </button>
              </div>
            )}

            {activeAssetTab === 'social' && (
              <div className="space-y-4">
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-bold text-gray-500 flex items-center gap-1">
                      <Twitter size={12} /> {t.twitterCaption}
                    </span>
                    <button
                      onClick={() => handleCopy(assets.sns.twitter || '', 'twitter')}
                      className="p-1 hover:bg-white/10 rounded"
                    >
                      {copiedField === 'twitter' ? <Check size={12} className="text-lime-400" /> : <Copy size={12} />}
                    </button>
                  </div>
                  <p className="text-sm text-gray-300">{assets.sns.twitter || ''}</p>
                </div>
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-bold text-gray-500 flex items-center gap-1">
                      <Linkedin size={12} /> {t.linkedinCaption}
                    </span>
                    <button
                      onClick={() => handleCopy(assets.sns.linkedin || '', 'linkedin')}
                      className="p-1 hover:bg-white/10 rounded"
                    >
                      {copiedField === 'linkedin' ? <Check size={12} className="text-lime-400" /> : <Copy size={12} />}
                    </button>
                  </div>
                  <p className="text-sm text-gray-300">{assets.sns.linkedin || ''}</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      <ChatModal
        isOpen={isChatOpen}
        onClose={() => setIsChatOpen(false)}
        videoTitle={metadata.title || ''}
        transcript={analysis.summary || ''}
        language={language}
      />
    </div>
  );
};

export default AnalysisDisplay;
